version: '3.8'

services:
  worker:
    restart: unless-stopped
    image: worker_image
    build:
      dockerfile: DockerfileWorker
    environment:
      - MONGO_LOGIN=admin
      - MONGO_PASSWORD=password
      - MONGO_HOST=mongo1
      - MONGO_PORT=27017
      - RABBITMQ_LOGIN=admin
      - RABBITMQ_PASSWORD=password
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_TIMEOUT=60000
    healthcheck:
      test: [ "CMD-SHELL", "curl --fail http://localhost:8081/health" ]
      interval: 30s
      timeout: 30s
      retries: 3
    depends_on:
      - manager
    networks:
      - crack-hash-net