version: '3.8'

services:
  haproxy:
    container_name: haproxy
    image: "haproxy:2.2-alpine"
    ports:
      - "27017:27017"
    volumes:
      - ./config/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
    networks:
      - crack-hash-net
networks:
  crack-hash-net:
